# Configuración básica del sitio
title: "Prueba de publicaciones"
email: "javier.dom.cal@gmail.com"
description: "Descripción breve de tu sitio"
baseurl: "/web_publications_modification" # El subdirectorio en el que se publicará tu sitio, por ejemplo /blog
url: "https://javierdomcal.github.io" # La URL base del sitio, cambiar si es necesario

# Exclude files and directories from the site
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Incluir la configuración de los plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Paginación de publicaciones
paginate: 10
paginate_path: "/publications/page:num/"

# Configuraciones de Markdown
markdown: kramdown
highlighter: rouge

# Configuraciones de salida
permalink: pretty

# Tema predeterminado
theme: jekyll-theme-primer

# Metadata de GitHub
github:
  is_project_page: true
