title: "Publications of Javier Dominguez Calonge"
description: "P치gina web de publicaciones de Javier Dominguez Calonge"
baseurl: "/web_publications_modification" # El subdirectorio donde se publicar치 tu sitio
url: "https://javierdomcal.github.io" # La URL base sin el subdirectorio

# Configuraci칩n de la colecci칩n de publicaciones
collections:
  publications:
    output: true
    permalink: /publications/:path/

plugins:
  - jekyll-paginate-v2

paginate_v2:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  collection: 'publications'
  sort_field: 'n'
  sort_reverse: true



# Tema de GitHub Pages
theme: jekyll-theme-primer
