title: "Publications of Javier Dominguez Calonge"
description: "Página web de publicaciones de Javier Dominguez Calonge"
baseurl: "/web_publications_modification" # El subdirectorio donde se publicará tu sitio
url: "https://javierdomcal.github.io" # La URL base sin el subdirectorio

# Habilitar las publicaciones de blog
collections:
  posts:
    output: true

# Configuración de la paginación
paginate: 10
paginate_path: "/page:num/"

# Plugins (si es necesario)
plugins:
  - jekyll-paginate

# Tema (cambia según lo que estés usando)
theme: jekyll-theme-minimal