title: "Publications of Javier Dominguez Calonge"
description: "Página web de publicaciones de Javier Dominguez Calonge"
baseurl: "/web_publications_modification" # El subdirectorio donde se publicará tu sitio
url: "https://javierdomcal.github.io" # La URL base sin el subdirectorio

# Configuración de la colección de publicaciones
collections:
  publications:
    output: true
    permalink: /publications/:path/

# Configuración de plugins soportados por GitHub Pages
plugins:
  - jekyll-paginate

# Paginación
paginate: 10
paginate_path: "/publications/page:num/"

# Tema de GitHub Pages
theme: jekyll-theme-primer
